import math

import pytest

from conftest import run_script, write_runs
from stats import compare_table, paired, summarize, t_crit


def run(i, name, seed, acc, tag="main", status="ok"):
    return {"run_id": f"e001-r{i:03d}", "exp": "e001", "name": name, "tag": tag, "seed": seed,
            "status": status, "metrics": {"acc": acc}, "duration_s": 60}


RUNS = [run(1, "smoke", None, 0.1, tag="smoke"),
        run(2, "baseline", 0, 0.70), run(3, "baseline", 1, 0.72), run(4, "baseline", 2, 0.71),
        run(5, "method", 0, 0.74), run(6, "method", 1, 0.75), run(7, "method", 2, 0.73),
        run(8, "method", 3, 0.99, status="failed")]


def test_summarize_known_values():
    s = summarize([1.0, 2.0, 3.0])
    assert s["n"] == 3 and s["mean"] == 2.0 and s["std"] == 1.0
    h = 4.303 / math.sqrt(3)
    assert s["lo"] == pytest.approx(2 - h) and s["hi"] == pytest.approx(2 + h)
    assert math.isnan(summarize([5.0])["std"]) and summarize([])["n"] == 0
    assert t_crit(1) == 12.706 and t_crit(100) == 1.96


def test_paired_matches_by_seed():
    p = paired({0: 1.0, 1: 2.0, 2: 3.0, 9: 0.0}, {0: 2.0, 1: 2.5, 2: 4.0, 5: 1.0})
    assert p["seeds"] == [0, 1, 2] and p["diffs"] == [1.0, 0.5, 1.0]
    assert p["b_wins"] == 3 and p["only_a"] == [9] and p["only_b"] == [5]
    assert p["boot_lo"] <= p["mean_diff"] <= p["boot_hi"]


def test_compare_table_flags_small_n():
    out = compare_table(RUNS[:3] + RUNS[4:6], "acc", "baseline", "method")
    assert "only 2 paired seed" in out


def test_ledger_table_and_figure(research, experiment, project):
    write_runs(experiment, RUNS)
    r = run_script("ledger.py", "table", "--exp", "e001", "--metric", "acc", cwd=project, check=True)
    assert "| baseline | 3 | 0.71 |" in r.stdout
    assert "smoke" not in r.stdout and "0.99" not in r.stdout   # smoke and failed runs excluded
    table = (experiment / "tables" / "acc-by-name.md").read_text()
    assert table.startswith("<!-- generated by ledger.py")
    run_script("ledger.py", "figure", "--exp", "e001", "--metric", "acc", cwd=project, check=True)
    svg = (experiment / "figures" / "acc-by-name.svg").read_text()
    assert "<svg" in svg and "baseline" in svg and "method" in svg
    r = run_script("stats.py", "compare", "--exp", "e001", "--metric", "acc", "--a", "baseline", "--b", "method",
                   "--out", "cmp.md", cwd=project, check=True)
    assert "3/3" in r.stdout and (experiment / "tables" / "cmp.md").exists()
    r = run_script("ledger.py", "budget", "--exp", "e001", cwd=project, check=True)
    assert "7 counted" in r.stdout and "max_runs=8" in r.stdout
    r = run_script("ledger.py", "show", "e001-r005", cwd=project, check=True)
    assert '"acc": 0.74' in r.stdout
